# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.2
  - 1.3

script:
  -                 julia --color=yes --project -e 'using Pkg; pkg"instantiate"; pkg"precompile"; Pkg.test(coverage=true)'
  -                 julia --color=yes --project -e 'using Pkg; pkg"dev Jive"' # Jive v0.1.14
  - JIVE_PROCS=auto julia --color=yes --project -e 'using Pkg; pkg"instantiate"; pkg"precompile"; Pkg.test()'

after_success:
  - if [[ "$TRAVIS_OS_NAME" == linux && "$TRAVIS_JULIA_VERSION" == 1.2 ]] ; then julia --project=. -e 'using Pkg;
                                                                                                       Pkg.add("Coverage");
                                                                                                       using Coverage;
                                                                                                       Codecov.submit(process_folder())' ; fi
