# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

julia:
  - 1.0
  - nightly

matrix:
  exclude:
    - os: osx
      julia: nightly

    - os: windows
      julia: nightly
      language: julia

  include:
    - os: osx

    - os: windows
      language: sh
      before_install:
        - choco install julia
        - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'
        - julia --color=yes -e 'using Pkg; pkg"add HTTP JSON2 MbedTLS URIParser Documenter Jive"'
        - julia --color=yes -e 'using Pkg; pkg"dev ."'
        - julia --color=yes -e 'using Pkg; pkg"precompile"'
      script:
        - cd test
        -                 julia --color=yes runtests.jl
        - JIVE_PROCS=auto julia --color=yes runtests.jl


script:
  -                 julia --color=yes --project=. -e 'using Pkg; pkg"instantiate"; pkg"precompile"; Pkg.test()'
  - JIVE_PROCS=auto julia --color=yes --project=. -e 'using Pkg; pkg"instantiate"; pkg"precompile"; Pkg.test()'

after_success:
  - if [[ "$TRAVIS_OS_NAME" == linux && "$TRAVIS_JULIA_VERSION" == nightly ]] ; then julia --project=. -e 'using Pkg;
                                                                                                           Pkg.add("Coverage");
                                                                                                           using Coverage;
                                                                                                           Codecov.submit(process_folder())' ; fi
